In [1]:
import pandas as pd

In [5]:
# Read datasets
fake_data = pd.read_csv("/content/Fake.csv")
true_data = pd.read_csv("/content/True.csv")

# Show first 5 rows
fake_data.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [6]:
print("Fake News Rows:", len(fake_data))
print("True News Rows:", len(true_data))

Fake News Rows: 23481
True News Rows: 21417

In [7]:
# Add labels
fake_data["label"] = "Fake"
true_data["label"] = "Real"

print(fake_data.head())

                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date label
0  December 31, 2017  Fake
1  December 31, 2017  Fake
2  December 30, 2017  Fake
3  December 29, 2017  Fake
4  December 25, 2017  Fake

In [8]:
# Combine both datasets
data = pd.concat([fake_data, true_data])

# Shuffle data
data = data.sample(frac=1)

# Show first 5 rows
data.head()

,title,text,subject,date,label
12970,Kazakh leader tells cabinet: Make state firms ...,ASTANA (Reuters) - Kazakh President Nursultan ...,worldnews,"December 6, 2017",Real
19906,HILLARY SUPPORTER AND MUSLIM IMMIGRANT Who Sho...,This story is a perfect example of why Barack ...,left-news,"Sep 28, 2016",Fake
19252,WATCH! TRUMP SUPPORTER “BIG JOE” Surrounded By...,https://www.youtube.com/watch?v=IPqrimR8GWw,left-news,"Jan 24, 2017",Fake
12317,KEY TRUMP ADVISOR: ELTON JOHN Will Perform At ...,Elton John will perform at Donald Trump s inau...,politics,"Nov 23, 2016",Fake
7027,Trump considering Representative Barletta for ...,(Reuters) - U.S. President-elect Donald Trump ...,politicsNews,"November 29, 2016",Real

In [9]:
# Keep only text and label columns
data = data[["text", "label"]]

# Show dataset
data.head()

                                                    text label
12970  ASTANA (Reuters) - Kazakh President Nursultan ...  Real
19906  This story is a perfect example of why Barack ...  Fake
19252        https://www.youtube.com/watch?v=IPqrimR8GWw  Fake
12317  Elton John will perform at Donald Trump s inau...  Fake
7027   (Reuters) - U.S. President-elect Donald Trump ...  Real

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [11]:
# Convert text into numbers
vectorizer = CountVectorizer()

x = vectorizer.fit_transform(data["text"])

y = data["label"]

In [12]:
# Split data
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

print("Data split completed!")

Data split completed!

In [13]:
# Train model
model = MultinomialNB()

model.fit(x_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [14]:
# Test news
news = ["Breaking: Aliens landed on Earth!"]

# Convert to numbers
news_vector = vectorizer.transform(news)

# Predict
result = model.predict(news_vector)

print("Prediction:", result[0])

Prediction: Fake

In [15]:
# Check accuracy
accuracy = model.score(x_test, y_test)

print("Accuracy:", accuracy * 100)

Accuracy: 95.42316258351893